### ISSUE TITLE
Hostname + Route53 internal DNS record with configurable values at creation

### ISSUE THREAD

**Issue by troal** [wazuh/wazuh-cloudformation#9]
Hi,
Would that be possible to change default Hostname + add corresponding Route53 internal DNS record with configurable values at server creation?
So the systems logs and ossec alerts contains the right hostname/beat.name values.
Thanks!

**Comment by manuasir** [comment]
Hello @troal ,

Thanks for this suggestion, we will evaluate the implementation and if decided, it will be included in the roadmap.
If you want to include it meanwhile, you can use something like this in your template:

```
  WazuhDataRecordSet:
    Condition: HasZone
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: !Join ['', [!Ref 'ParentDomainName', .]]
      Name: !Join ['', [data., !Ref 'SubDomainName', ., !Ref 'ParentDomainName', .]]
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt ElbWazuh.CanonicalHostedZoneNameID
        DNSName: !GetAtt ElbWazuh.DNSName
```
Further information [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html).

Regards
